version: '3'
services:
  wallabag:
    # https://hub.docker.com/r/wallabag/wallabag
    container_name: $SERVICE
    image: wallabag/wallabag
    restart: $RESTART_POLICY
    environment:
      - SYMFONY__ENV__LOCALE=de
      - SYMFONY__ENV__DOMAIN_NAME=https://$SERVICE.$DOMAIN_EXTERN
      # Mail settings:
      - SYMFONY__ENV__FROM_EMAIL=$FROM_EMAIL
      - SYMFONY__ENV__MAILER_HOST=$MAILER_HOST
      - SYMFONY__ENV__MAILER_PASSWORD=$MAILER_PASSWORD
      - SYMFONY__ENV__MAILER_USER=$MAILER_USER
      # DB Settings:
      - POPULATE_DATABASE=true
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=wallabag
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_HOST=${SERVICE}_pg
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=$DB_PASS
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_USER=wallabag
      # Network settings:
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=$SERVICE.$DOMAIN_EXTERN
      - VIRTUAL_HOST=$SERVICE.$DOMAIN_EXTERN
      - VIRTUAL_PORT=80
    #ports:
    #    - "80"
    volumes:
      - $STACK_DATA/$SERVICE/images:/var/www/wallabag/web/assets/images
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frontend
      - wallabag_net
    depends_on:
      - wallabag_pg

  wallabag_pg:
    container_name: ${SERVICE}_pg
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=wallabag
        #- POSTGRES_DB=wallabag
    volumes:
      - $STACK_DATA/$SERVICE/pg/:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
    - wallabag_net

networks:
  frontend:
    external:
      name: frontend
  wallabag_net: