version: '2.2'
services:

  nextcloud:
    # Source: https://hub.docker.com/_/nextcloud/
    container_name: ${SERVICE}
    image: nextcloud:${VERSION}-fpm-alpine
    # If the mem_limit is not set nextcloud will grab as much memory as possible:
    mem_limit: 2048m
    mem_reservation: 512m
    environment:
      - REDIS_HOST=${SERVICE}_redis
    env_file:
      - ${HOSTNAME}.env
    extra_hosts:
      - mailbox.$DOMAIN:$DOCKER_HOST_IP
    volumes:
        # Main folder needed for updating:
      - $DATA/${SERVICE}/html:/var/www/html
        # local configuration
      - $DATA/${SERVICE}/config:/var/www/html/config
        # Installed / modified apps
      - $DATA/${SERVICE}/custom_apps:/var/www/html/custom_apps
        # the actual data of the Nextcloud: 
        #- $DATA/${SERVICE}/data:/var/www/html/data
        # themeing / branding
      - $DATA/${SERVICE}/themes:/var/www/html/themes

        # the actual data of nextcloud
      - $NEXTDATA:/var/www/html/data
        # private video folder:
      - $NEXTVIDEO:/mnt/videos:ro 
        # private audio file folder:
      - $NEXTAUDIO:/mnt/audio:ro
        # private music file folder:
      - $NEXTMUSIC:/mnt/musik:ro

        # Custom settings for php fpm to make nextcloud work. The default settings resulted in the error:
        # WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
      - $WS_DOCKER/${SERVICE}/etc/www-custom.ini:/usr/local/etc/php-fpm.d/zz-custom.conf
    networks:
      # frontend is used to communicate with the mailbox container
      - frontend
      - nextcloud_net
    depends_on:
      - nextcloud_db
      - nextcloud_redis
  
  nextcloud_fe:
    image: nginx:mainline-alpine
    container_name: ${SERVICE}_fe
    volumes:
      - $DATA/${SERVICE}/html:/var/www/html:ro
      - $WS_DOCKER/${SERVICE}/etc/nginx.conf:/etc/nginx/nginx.conf
    environment:
      ### Virtual host
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=${SUBDOMAIN}.$DOMAIN
      - VIRTUAL_HOST=${SUBDOMAIN}.$DOMAIN
      - VIRTUAL_PORT=80
    extra_hosts:
      - mailbox.$DOMAIN:$DOCKER_HOST_IP
    depends_on:
      - nextcloud
    networks:
      - frontend
      - nextcloud_net

  nextcloud_db:
    container_name: ${SERVICE}_db
    image: percona:5.7
    env_file:
      - ${HOSTNAME}.env
    volumes:
      - $DATA/${SERVICE}/mysql/lib:/var/lib/mysql
      - $DATA/${SERVICE}/mysql/log:/var/log/mysql
      - $WS_DOCKER/${SERVICE}/my.cnf.d:/etc/my.cnf.d 
      - /etc/localtime:/etc/localtime:ro      
    networks:
      - nextcloud_net

  # Redis leads to _drastic_ performance improvements:
  nextcloud_redis:
    container_name: ${SERVICE}_redis
    image: redis:alpine
    mem_limit: 2048m
    mem_reservation: 512m
    networks:
      - nextcloud_net

networks:
  frontend:
    external:
      name: frontend
  nextcloud_net:
