version: '3'
services:

  nextcloud:
    container_name: nextcloud
    image: nextcloud:16-apache
    # If the mem_limit is not set nextcloud will grab as much memory as possible:
    mem_limit: 2048m
    mem_reservation: 512m
    env_file:
      - ${HOSTNAME}
    environment:
      ### Virtual host
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=next.$DOMAIN
      - VIRTUAL_HOST=next.$DOMAIN
      - VIRTUAL_PORT=80
    extra_hosts:
      - mailbox.$DOMAIN:$DOCKER_HOST_IP
    volumes:
        # Main folder needed for updating:
      - $DATA/nextcloud/html:/var/www/html
        # local configuration
      - $DATA/nextcloud/config:/var/www/html/config
        # Installed / modified apps
      - $DATA/nextcloud/custom_apps:/var/www/html/custom_apps
        # the actual data of the Nextcloud: 
        #- $DATA/nextcloud/data:/var/www/html/data
        # themeing / branding
      - $DATA/nextcloud/themes:/var/www/html/themes

        # the actual data of nextcloud
      - $NEXTDATA:/var/www/html/data
        # private video folder:
      - $NEXTVIDEO:/mnt/videos:ro 
        # private audio file folder:
      - $NEXTAUDIO:/mnt/audio:ro
        # private music file folder:
      - $NEXTMUSIC:/mnt/musik:ro
    networks:
      - frontend
      - nextcloud_net
    depends_on:
      - nextcloud_db

  nextcloud_db:
    container_name: nextcloud_db
    image: percona:5.7
    env_file:
      - ${HOSTNAME}.env
    volumes:
      - $DATA/nextcloud/mysql/lib:/var/lib/mysql
      - $DATA/nextcloud/mysql/log:/var/log/mysql
      - $WS_DOCKER/nextcloud/my.cnf.d:/etc/my.cnf.d 
      - /etc/localtime:/etc/localtime:ro      
    networks:
      - nextcloud_net

networks:
  frontend:
    external:
      name: frontend
  nextcloud_net:
