---
version: '3'
services:
  registry:
    container_name: $SERVICE
    image: registry:2
    restart: unless-stopped
    env_file:
      - $SERVICE.env
    environment:
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=$SERVICE.$DOMAIN
      - VIRTUAL_HOST=$SERVICE.$DOMAIN
      - VIRTUAL_PORT=5000
      - NETWORK_ACCESS=internal
    ports:
      - 5000
    volumes:
      - $DATA/$SERVICE/data:/var/lib/registry
    networks:
      - frontend

networks:
  frontend:
    external:
      name: frontend
