version: '2.2'
services:
  # https://hub.docker.com/r/onlyoffice/communityserver/
  onlyoffice-community-server:
    container_name: ${SERVICE}-community-server
    image: onlyoffice/communityserver:latest
    restart: $RESTART_POLICY
    depends_on:
     - onlyoffice_pg
     - onlyoffice-document-server
    mem_limit: 4096m
    mem_reservation: 2048m
    environment:
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
     - MAIL_SERVER_ENABLED=false
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     # DB settings:
     - POSTGRESQL_SERVER_DB_NAME=$ONLYOFFICE_DB
     - POSTGRESQL_SERVER_HOST=${SERVICE}_pg
     - POSTGRESQL_SERVER_PASS=$ONLYOFFICE_DB_PASS
     - POSTGRESQL_SERVER_PORT=5432
     - POSTGRESQL_SERVER_USER=$ONLYOFFICE_DB_USER
     # Network settings:
     - LETSENCRYPT_EMAIL=$ADMIN_MAIL
     - LETSENCRYPT_HOST=$SERVICE.$DOMAIN_EXTERN
     - NETWORK_ACCESS=internal
     - VIRTUAL_HOST=onlyoffice.$DOMAIN_EXTERN
     - VIRTUAL_PORT=80
    networks:
     - frontend
     - onlyoffice
    stdin_open: true
    tty: true
    volumes:
     - $STACK_DATA/$SERVICE/community_data:/var/www/onlyoffice/Data
     - $STACK_DATA/$SERVICE/community_log:/var/log/onlyoffice
     - $STACK_DATA/$SERVICE/document_data:/var/www/onlyoffice/DocumentServerData
     - $STACK_DATA/$SERVICE/certs:/var/www/onlyoffice/Data/certs
     - $STACK_DATA/$SERVICE/postgres:/var/lib/postgresql
    depends_on:
      - onlyoffice_pg

  # https://hub.docker.com/r/onlyoffice/documentserver/
  onlyoffice-document-server:
    mem_limit: 4096m
    mem_reservation: 2048m
    container_name: ${SERVICE}-document-server
    image: onlyoffice/documentserver:latest
    restart: $RESTART_POLICY
    stdin_open: true
    tty: true
    networks:
      - frontend
      - onlyoffice
      - nextcloud_net
    environment:
     - REDIS_SERVER_HOST=${SERVICE}_redis
     - REDIS_SERVER_PORT=6379
     # Network settings:
     #- NETWORK_ACCESS=internal
     - LETSENCRYPT_EMAIL=$ADMIN_MAIL
     - LETSENCRYPT_HOST=onlyoffice-document-server.$DOMAIN_EXTERN
     - VIRTUAL_HOST=onlyoffice-document-server.$DOMAIN_EXTERN
     - VIRTUAL_PORT=80
    volumes:
       - $STACK_DATA/$SERVICE/document_data:/var/www/onlyoffice/Data
       - $STACK_DATA/$SERVICE/document_log:/var/log/onlyoffice
       - $STACK_DATA/$SERVICE/document_fonts:/usr/share/fonts/truetype/custom
       - $STACK_DATA/$SERVICE/document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
    depends_on:
      - onlyoffice_redis

  onlyoffice_pg:
    container_name: ${SERVICE}_pg
    image: postgres:12-alpine
    restart: $RESTART_POLICY
    environment:
      - POSTGRES_USER=$ONLYOFFICE_DB_USER
      - POSTGRES_DB=$ONLYOFFICE_DB
      - POSTGRES_PASSWORD=$ONLYOFFICE_DB_PASS
    volumes:
      - $STACK_DATA/$SERVICE/pg/:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - onlyoffice

  onlyoffice_redis:
    container_name: ${SERVICE}_redis
    image: redis:alpine
    restart: $RESTART_POLICY
    mem_limit: 2048m
    mem_reservation: 512m
    networks:
      - onlyoffice

networks:
  onlyoffice:
  frontend:
    external:
      name: frontend
  nextcloud_net:
    external:
      name: nextcloud_nextcloud_net