version: '2.2'
services:
  onlyoffice-community-server:
    container_name: ${SERVICE}-community-server
    image: onlyoffice/communityserver:latest
    depends_on:
     - onlyoffice_pg
     - onlyoffice-document-server
    mem_limit: 4096m
    mem_reservation: 2048m
    environment:
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
     - LETSENCRYPT_EMAIL=$ADMIN_MAIL
     - LETSENCRYPT_HOST=$SERVICE.$DOMAIN
     - MAIL_SERVER_ENABLED=false
     #- NETWORK_ACCESS=internal
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     - POSTGRESQL_SERVER_DB_NAME=$ONLYOFFICE_DB
     - POSTGRESQL_SERVER_HOST=${SERVICE}_pg
     - POSTGRESQL_SERVER_PASS=$ONLYOFFICE_DB_PASS
     - POSTGRESQL_SERVER_PORT=5432
     - POSTGRESQL_SERVER_USER=$ONLYOFFICE_DB_USER
     - VIRTUAL_HOST=onlyoffice.$DOMAIN
     - VIRTUAL_PORT=80
    networks:
     - frontend
     - onlyoffice
    ports:
     - 80
     - 443
     - 5222
    #extra_hosts:
    # - next.lindenbox.de:10.1.1.6
    stdin_open: true
    tty: true
    volumes:
     - $DATA/$SERVICE/community_data:/var/www/onlyoffice/Data
     - $DATA/$SERVICE/community_log:/var/log/onlyoffice
     - $DATA/$SERVICE/document_data:/var/www/onlyoffice/DocumentServerData
     - $DATA/$SERVICE/certs:/var/www/onlyoffice/Data/certs
     - $DATA/$SERVICE/postgres:/var/lib/postgresql
    depends_on:
      - onlyoffice_pg

  onlyoffice-document-server:
    mem_limit: 4096m
    mem_reservation: 2048m
    container_name: ${SERVICE}-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    networks:
      - frontend
      - onlyoffice
      - nextcloud_net
    environment:
     #- NETWORK_ACCESS=internal
     - LETSENCRYPT_EMAIL=$ADMIN_MAIL
     - LETSENCRYPT_HOST=onlyoffice-document-server.$DOMAIN
     - REDIS_SERVER_HOST=${SERVICE}_redis
     - REDIS_SERVER_PORT=6379
     - VIRTUAL_HOST=onlyoffice-document-server.$DOMAIN
     - VIRTUAL_PORT=80
    volumes:
       - $DATA/$SERVICE/document_data:/var/www/onlyoffice/Data
       - $DATA/$SERVICE/document_log:/var/log/onlyoffice
       - $DATA/$SERVICE/document_fonts:/usr/share/fonts/truetype/custom
       - $DATA/$SERVICE/document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
    depends_on:
      - onlyoffice_redis

  onlyoffice_pg:
    container_name: ${SERVICE}_pg
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=$ONLYOFFICE_DB_USER
      - POSTGRES_DB=$ONLYOFFICE_DB
      - POSTGRES_PASSWORD=$ONLYOFFICE_DB_PASS
    volumes:
      - $DATA/${SERVICE}/pg/:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - onlyoffice

  onlyoffice_redis:
    container_name: ${SERVICE}_redis
    image: redis:alpine
    mem_limit: 2048m
    mem_reservation: 512m
    networks:
      - onlyoffice

networks:
  onlyoffice:
  frontend:
    external:
      name: frontend
  nextcloud_net:
    external:
      name: nextcloud_nextcloud_net
