version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.14.1
    volumes:
      - $DATA/$SERVICE/elastic_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - elk
  kibana:
    image: kibana:7.14.1
    environment:
      ### Virtual host
      #- LETSENCRYPT_EMAIL=$ADMIN_MAIL
      #- LETSENCRYPT_HOST=kibana.$DOMAIN
      - NETWORK_ACCESS=internal
      - VIRTUAL_HOST=kibana.$DOMAIN
      - VIRTUAL_PORT=5601
      - SELF_SIGNED_HOST=kibana.$DOMAIN
    networks:
      - frontend
      - elk

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    user: root
    volumes:
      - /$WS_DOCKER/${SERVICE}/etc/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk

  nginx_for_elk:
    image: nginx
    volumes:
      - $WS_DOCKER/$SERVICE/etc/nginx.conf:/etc/nginx/nginx.conf
      - $WS_DOCKER/$SERVICE/etc/htpasswd:/etc/nginx/htpasswd
    ports:
      - 9200:9200
    networks:
      - elk

networks:
  frontend:
    external:
      name: frontend
  elk:
