version: '3'
services:
  infraweb:
    image: nginx:stable-alpine
    container_name: $SERVICE
    volumes:
      - $WS_DOCKER/$SERVICE:/usr/share/nginx/html
    environment:
      ### Webfrontend settings:
      - VIRTUAL_HOST=$SERVICE.$DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
    networks:
      - frontend

networks:
  frontend:
    external:
      name: frontend
