version: '3'
services:
  unbound:
    container_name: unbound
    hostname: unbound
    image: mvance/unbound:latest
    restart: $RESTART_POLICY
    networks:
      pubnet:
        ipv4_address: $UnboundIP
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    restart: $RESTART_POLICY
    #    env_file:
    #  - pihole.env
    environment:
      # Without DNSMASQ_LISTENING=all dnsmasq does not answer to dns requests
      - DNSMASQ_LISTENING=all
      - VIRTUAL_HOST=pihole.$LOCAL_DOMAIN
      - SELF_SIGNED_HOST=pihole.$LOCAL_DOMAIN
      - VIRTUAL_PORT=80
      # We want this service not be accessible from the internet:
      - NETWORK_ACCESS=internal
      - PIHOLE_DOMAIN=$LOCAL_DOMAIN
      # Pihole specific variables:
      - CONDITIONAL_FORWARDING=$REV_SERVER
      - CONDITIONAL_FORWARDING_DOMAIN=$REV_SERVER_DOMAIN
      - CONDITIONAL_FORWARDING_IP=$REV_SERVER_TARGET
      - CONDITIONAL_FORWARDING_REVERSE=$REV_SERVER_CIDR
      - DHCP_ACTIVE=$DHCP_ACTIVE
      - DHCP_START=$DHCP_START
      - DHCP_END=$DHCP_END
      - DHCP_ROUTER=$DHCP_ROUTER
      - DHCP_IPv6=$DHCP_IPv6
      - IPv6=$IPv6
      - DNS1=$DNS1
      - DNS2=$DNS2
      - DNSSEC=$DNSSEC
      - FTLCONF_LOCAL_IPV4=$FTLCONF_REPLY_ADDR4
      - TZ=$TZ
      - WEBPASSWORD=$WEBPASSWORD
    volumes:
      - $STACK_DATA/pihole/etc:/etc/pihole
      - $STACK_DATA/pihole/dnsmasq.d:/etc/dnsmasq.d
      # List with own hosts entries (eg. for wpad / proxy autocnfig)
      #- $STACK_CONF/pihole/etc/pihole/lan.list:/etc/pihole/lan.list
      # This files sources the lan.list
      #- $STACK_CONF/pihole/etc/dnsmasq.d/02-lan.conf:/etc/dnsmasq.d/02-lan.conf
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    networks:
      frontend:
      pubnet:
        ipv4_address: $ServerIP

networks:
  frontend:
    external:
      name: frontend
  pubnet:
    external:
      name: pub_net
