version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - ${HOST}.env
    environment:
      # Without DNSMASQ_LISTENING=all dnsmasq does not answer to dns requests
      - DNSMASQ_LISTENING=all 
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=pihole.$DOMAIN
      - VIRTUAL_HOST=pihole.$DOMAIN
      - VIRTUAL_PORT=80
      # We want this service not be accessible from the internet:
      - NETWORK_ACCESS=internal
    volumes:
      # For general settings
      - pihole_etc:/etc/pihole
      # List with own hosts entries (eg. for wpad / proxy autocnfig)
      - $WS_DOCKER/pihole/etc/pihole/lan.list:/etc/pihole/lan.list
      # This files sources the lan.list
      - $WS_DOCKER/pihole/etc/dnsmasq.d/02-lan.conf:/etc/dnsmasq.d/02-lan.conf
    networks:
      frontend:
      pubnet:
        ipv4_address: $ServerIP

networks:
  frontend:
    external:
      name: frontend
  pubnet:
    external:
      name: pub_net

volumes:
  pihole_etc:
