version: '3'
# https://hub.docker.com/r/skyr0/ttrss
services:
  ttrss:
    container_name: $SERVICE
    image: skyr0/ttrss
    restart: $RESTART_POLICY
    environment:
      - BASE_URL=https://$SUBDOMAIN.$DOMAIN_EXTERN
      # DB settings:
      - DB_TYPE=$DB_TYPE
      - DB_NAME=$SERVICE
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=${SERVICE}_pg
      # Network settings:
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=$SUBDOMAIN.$DOMAIN_EXTERN
      - VIRTUAL_HOST=$SUBDOMAIN.$DOMAIN_EXTERN
      - VIRTUAL_PORT=8080
    volumes:
      - $STACK_DATA/$SERVICE/config:/var/www/ttrss/docker
    depends_on:
      - ttrss_pg
    networks:
      - frontend
      - ttrss_net

  ttrss_pg:
    container_name: ${SERVICE}_pg
    image: postgres:12-alpine
    restart: $RESTART_POLICY
    environment:
      - POSTGRES_DB=$SERVICE
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
    volumes:
      - $STACK_DATA/${SERVICE}/pg/:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro      
    networks:
    - ttrss_net

networks:
  frontend:
    external:
      name: frontend
  ttrss_net:
