version: '3'
services:
  ttrss:
    image: skyr0/ttrss
    container_name: $SERVICE
    env_file:
      - ${HOSTNAME}.env
    environment:
      - BASE_URL=https://$SUBDOMAIN.$DOMAIN
        #- SELF_URL_PATH=https://$SUBDOMAIN.$DOMAIN
      - DB_HOST=${SERVICE}_pg
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=$SUBDOMAIN.$DOMAIN
      - VIRTUAL_HOST=$SUBDOMAIN.$DOMAIN
      - VIRTUAL_PORT=8080
    volumes:
      - $DATA/$SERVICE/config:/var/www/ttrss/docker
    depends_on:
      - ttrss_pg
    networks:
      - frontend
      - ttrss_net

  ttrss_pg:
    container_name: ${SERVICE}_pg
    image: postgres:12-alpine
    env_file:
      - ${HOSTNAME}.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
    volumes:
      - $DATA/${SERVICE}/pg/:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro      
    networks:
    - ttrss_net



networks:
  frontend:
    external:
      name: frontend
  ttrss_net:
