version: '3'
services:
  bitwarden_rs:
    container_name: $SERVICE
    image:  vaultwarden/server:alpine
    restart: $RESTART_POLICY
    environment:
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=rustbit.$DOMAIN_EXTERN
      - VIRTUAL_HOST=rustbit.$DOMAIN_EXTERN
      - VIRTUAL_PORT=80
      #- NETWORK_ACCESS=internal
    volumes:
      - $STACK_DATA/$SERVICE/:/data
    networks:
      frontend:

networks:
  frontend:
    external:
      name: frontend
