version: '3'
services:
  bitwarden_rs:
    container_name: bitwarden_rs
    image: bitwardenrs/server:alpine
    environment:
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=rustbit.$DOMAIN
      - VIRTUAL_HOST=rustbit.$DOMAIN
      - VIRTUAL_PORT=80
      #- NETWORK_ACCESS=internal
    volumes:
      - $DATA/bitwarden_rs/:/data
    networks:
      frontend:

networks:
  frontend:
    external:
      name: frontend
