version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest  # use "raspberry-pi" instead of "latest" for arm devices
    #network_mode: host
    container_name: $SERVICE
    expose:
      # For homebridge we need the expose to work with nginx-proxy:
      - 8080
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - NETWORK_ACCESS=internal
      - VIRTUAL_HOST=$SERVICE.$LOCAL_DOMAIN
      - VIRTUAL_PORT=8080
      - SELF_SIGNED_HOST=SERVICE.$LOCAL_DOMAIN
    volumes:
      - $DATA/$SERVICE:/homebridge
    networks:
      frontend:
      pubnet:
        ipv4_address: $IP_HOMEBRIDGE

networks:
  frontend:
    external:
      name: frontend
  pubnet:
    external:
      name: pub_net
