version: '3'
services:
  privoxy:
    build: .
    container_name: privoxy
    volumes:
      - $WS_DOCKER/privoxy/etc/config:/etc/privoxy/config
    networks:
      pubnet:
        ipv4_address: $PROXY_IP

  nginx_wpad:
    image: nginx:alpine
    container_name: nginx_wpad
    volumes:
      - $WS_DOCKER/privoxy/etc/proxy.pac:/usr/share/nginx/html/proxy.pac
    environment:
      ### Webfrontend settings:
      - VIRTUAL_HOST=wpad.fritz.box
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
    networks:
      - frontend

networks:
  pubnet:
    external:
      name: pub_net
  frontend:
    external:
      name: frontend
