version: '2.2'
services:

  onlyengine:
    container_name: onlyengine
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    networks:
      - frontend
    environment:
     - LETSENCRYPT_EMAIL=$ADMIN_MAIL
     - LETSENCRYPT_HOST=onlyengine.$DOMAIN
     - VIRTUAL_HOST=onlyengine.$DOMAIN
     - VIRTUAL_PORT=80
    volumes:
       - $DATA/only_engine/data:/var/www/onlyoffice/Data
       - $DATA/only_engine/log:/var/log/onlyoffice
       - $DATA/only_engine/fonts:/usr/share/fonts/truetype/custom
       - $DATA/only_engine/forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten

networks:
  frontend:
    external:
      name: frontend
