---
version: '2.0'
services:
  # Source: https://hub.docker.com/r/jwilder/nginx-proxy/
  nginx-proxy:
    container_name: nginx-proxy
    image: "jwilder/nginx-proxy:alpine"
    env_file:
      - general.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # folder for let's encrypt certs:
      - $DATA/nginx-proxy/certs:/etc/nginx/certs
      # Here we can store extra nginx parameter for the virtual hosts:
      - $WS_DOCKER/nginx-proxy/etc/vhost.d:/etc/nginx/vhost.d
      # This file is for defining the networks which are considered as private
      - $WS_DOCKER/nginx-proxy/etc/network_internal.conf:/etc/nginx/network_internal.conf
      ### This may be used to write challange file:
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      # This label is used to tell letsencrpyt container to which nginx-proxy it has to connect:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      frontend:
#      pubnet:
#        ipv4_address: $FRONTEND_IP

networks:
  frontend:
    external:
      name: frontend
      #  pubnet:
      #    external:
      #      name: pub_net
