---
version: '2.0'
services:
  # Source: https://hub.docker.com/r/jwilder/nginx-proxy/
  nginx-proxy:
    container_name: $SERVICE
    image: "jwilder/nginx-proxy:alpine"
    env_file:
      - ${HOSTNAME}.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # folder for let's encrypt certs:
      - $DATA/$SERVICE/certs:/etc/nginx/certs
      # Here we can store extra nginx parameter for the virtual hosts:
      - $WS_DOCKER/$SERVICE/etc/vhost.d:/etc/nginx/vhost.d
      # This file is for defining the networks which are considered as private
      - $WS_DOCKER/$SERVICE/etc/network_internal.conf:/etc/nginx/network_internal.conf
      ### This may be used to write challange file:
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      # This label is used to tell letsencrpyt container to which nginx-proxy it has to connect:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      frontend:
      pubnet:
        ipv4_address: $FRONTEND_IP

  # Source: https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/
  letsencrypt:
    image: jrcs/letsencrypt-${SERVICE}-companion
    volumes:
      # The companion write the certs into the nginx certs dir.
      - $DATA/$SERVICE/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

networks:
  frontend:
    external:
      name: frontend
  pubnet:
    external:
      name: pub_net
