version: '3'
services:
  # Source: https://hub.docker.com/r/mazzolino/tiddlywiki
  tiddlywiki:
    container_name: $SERVICE
    image: mazzolino/tiddlywiki
    restart: $RESTART_POLICY
    environment:
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=$SUBDOMAIN.$DOMAIN_EXTERN
      - VIRTUAL_HOST=$SUBDOMAIN.$DOMAIN_EXTERN
      - VIRTUAL_PORT=8080
      # Tiddlywiki specific variables:
      - USERNAME=$USERNAME
      - PASSWORD=$PASSWORD
    volumes:
      - $STACK_DATA/$SERVICE:/var/lib/tiddlywiki
    networks:
      - frontend

networks:
  frontend:
    external:
      name: frontend
