version: '3'
services:
  # Source: https://hub.docker.com/r/mazzolino/tiddlywiki
  tiddlywiki:
    container_name: tiddlywiki
    image: mazzolino/tiddlywiki
    env_file:
      - tiddlywiki.env
    environment:
      - LETSENCRYPT_EMAIL=$ADMIN_MAIL
      - LETSENCRYPT_HOST=$SUBDOMAIN.$DOMAIN
      - VIRTUAL_HOST=$SUBDOMAIN.$DOMAIN
      - VIRTUAL_PORT=8080
    volumes:
      - $DATA/tiddlywiki:/var/lib/tiddlywiki
    networks:
      - frontend

networks:
  frontend:
    external:
      name: frontend
